```{r, eval = FALSE}
filename <- "National_Downloadable_File.csv"
if (!file.exists(filename) {
    download.file("https://data.medicare.gov/views/bg9k-emty/files/QE8tOSxD5tVVN7LcpQE7s9BU4zNsegwD7nJgJLNOaaQ?filename=Physician_Compare_Databases.zip&content_type=application%2Fzip%3B%20charset%3Dbinary", destfile = "Physician_Compare_Databases")
    setwd("C:/Users/knarf/Desktop")
    unzipped <- unzip("Physician_Compare_Databases.zip", file = "Physician_Compare_Databases/National_Downloadable_File.csv")
    phys <- read.csv(unzipped)
    }
}
```

```{r}
set.seed(5847)
phys_small <- phys[sample(nrow(phys), 2000), ]
```

# Research Questions

1. What are the characteristics of Medicare physicians who use EHR?

2. Do certain types of medical training / medical school and graduation time period affect whether or not Medicare physicians use EHR?

```{r}
des_col <- c(9:20, 24:25, 37:40)
clean <- phys_small[, des_col]
```

```{r}
no_ehr <- clean[clean$Participating.in.EHR == "N", ]
yes_ehr <- clean[clean$Participating.in.EHR == "Y", ]
```





